name: Inventory DevSecOps Security Pipeline

on:
  push:
    branches:
      - devsecops-integration

  pull_request:
    branches:
      - devsecops-integration

permissions:
  contents: read

jobs:
  security-scan:
    name: DevSecOps Security Scan
    runs-on: ubuntu-latest

    steps:

      # =========================================================
      # 1. CHECKOUT SOURCE CODE
      # =========================================================
      - name: Checkout Source Code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262


      # =========================================================
      # 2. SECRET SCANNING - GITLEAKS
      # =========================================================
      - name: Run GitLeaks
        run: |
          docker run --rm \
            -v "$PWD:/repo" \
            zricethezav/gitleaks:latest \
            detect \
            --source=/repo \
            --no-git \
            --verbose


      # =========================================================
      # 3. STATIC APPLICATION SECURITY TESTING - SEMGREP
      # =========================================================
      - name: Run Semgrep
        run: |
          docker run --rm \
            -v "$PWD:/src" \
            semgrep/semgrep \
            semgrep scan \
            --config=auto \
            --error \
            --exclude '.github/workflows/test.yml' \
            --exclude '.github/workflows/deploy-dit.yml' \
            --exclude 'src/contexts/UserContext.tsx' \
            --exclude 'db/seed/R__seed_dev_data.sql' \
            --exclude 'k6/seed/load-users.sql' \
            /src

      # 4. DEPENDENCY VULNERABILITY SCANNING
      - name: Run OWASP Dependency-Check
        shell: bash
        run: |
          set -euo pipefail

          rm -rf dependency-check-report
          mkdir -p dependency-check-report

          DATA_DIR="$(mktemp -d)"

          docker run --rm \
            -v "$PWD:/src" \
            -v "$DATA_DIR:/usr/share/dependency-check/data" \
            owasp/dependency-check:12.1.0 \
            --project "Inventory Management" \
            --scan /src/package-lock.json \
            --format HTML \
            --format JSON \
            --out /src/dependency-check-report \
            --disableAssembly
